{
 "title": "Service Simulator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((sum(rate(request_time_ms_count{error=\"true\"}[1m])) by (job)) / (sum(rate(request_time_ms_count[1m])) by (job))))"
    },
    { "expr": "99.95", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_time_ms_count[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(request_time_ms{quantile=\"0.9\"}) by (job)",
     "legendFormat": "p9"
    },
    {
     "expr": "max(request_time_ms{quantile=\"0.99\"}) by (job)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Requests by Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_time_ms_count[1m])) by (code,job)"
    }
   ]
  },
  {
   "title": "Errors by Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_time_ms_count{error=\"true\"}[1m])) by (code, job)"
    }
   ]
  },
  {
   "title": "Requests by Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_time_ms_count{node=~\".*\"}[1m])) by (node)"
    }
   ]
  }
 ]
}